//该头文件由软件自动生成，请勿随意修改！
#ifndef _UI_H
#define _UI_H

#define UI_BUF_0FONT_FONT_ASC_BIN                  UI_ADDR_BASE(0x0)
#define UI_LEN_0FONT_FONT_ASC_BIN                  0x3033

#define UI_BUF_0FONT_FONT_NUM_38_BIN               UI_ADDR_BASE(0x3033)
#define UI_LEN_0FONT_FONT_NUM_38_BIN               0x35d9

#define UI_BUF_0GPU_GPU_BIN                        UI_ADDR_BASE(0x660c)
#define UI_LEN_0GPU_GPU_BIN                        0xd000

#define UI_BUF_FONT_BIN_FONT_SIZE_11_BIN           UI_ADDR_BASE(0x1360c)
#define UI_LEN_FONT_BIN_FONT_SIZE_11_BIN           0x8cb3

#define UI_BUF_FONT_BIN_FONT_SIZE_15_BIN           UI_ADDR_BASE(0x1c2bf)
#define UI_LEN_FONT_BIN_FONT_SIZE_15_BIN           0xa86d

#define UI_BUF_FONT_BIN_FONT_SIZE_17_BIN           UI_ADDR_BASE(0x26b2c)
#define UI_LEN_FONT_BIN_FONT_SIZE_17_BIN           0xb8a3

#define UI_BUF_FONT_BIN_FONT_SIZE_22_BIN           UI_ADDR_BASE(0x323cf)
#define UI_LEN_FONT_BIN_FONT_SIZE_22_BIN           0xf37a

#define UI_BUF_ICON_ACTIVITY_BIN                   UI_ADDR_BASE(0x41749)
#define UI_LEN_ICON_ACTIVITY_BIN                   0x13c3

#define UI_BUF_IMAGE_BIN_BACK_BIN                  UI_ADDR_BASE(0x42b0c)
#define UI_LEN_IMAGE_BIN_BACK_BIN                  0x13a

#define UI_BUF_IMAGE_BIN_BATTERY_LEVEL_1_BIN       UI_ADDR_BASE(0x42c46)
#define UI_LEN_IMAGE_BIN_BATTERY_LEVEL_1_BIN       0x1c6

#define UI_BUF_IMAGE_BIN_BATTERY_LEVEL_2_BIN       UI_ADDR_BASE(0x42e0c)
#define UI_LEN_IMAGE_BIN_BATTERY_LEVEL_2_BIN       0x1c6

#define UI_BUF_IMAGE_BIN_BATTERY_LEVEL_3_BIN       UI_ADDR_BASE(0x42fd2)
#define UI_LEN_IMAGE_BIN_BATTERY_LEVEL_3_BIN       0x1d6

#define UI_BUF_IMAGE_BIN_BATTERY_LEVEL_4_BIN       UI_ADDR_BASE(0x431a8)
#define UI_LEN_IMAGE_BIN_BATTERY_LEVEL_4_BIN       0x1d6

#define UI_BUF_IMAGE_BIN_BATTERY_LEVEL_5_BIN       UI_ADDR_BASE(0x4337e)
#define UI_LEN_IMAGE_BIN_BATTERY_LEVEL_5_BIN       0x1d6

#define UI_BUF_IMAGE_BIN_BOTTON_CLICK_BIN          UI_ADDR_BASE(0x43554)
#define UI_LEN_IMAGE_BIN_BOTTON_CLICK_BIN          0x319

#define UI_BUF_IMAGE_BIN_BOTTON_UNCLICK_BIN        UI_ADDR_BASE(0x4386d)
#define UI_LEN_IMAGE_BIN_BOTTON_UNCLICK_BIN        0x319

#define UI_BUF_IMAGE_BIN_CHECK_MARK_BIN            UI_ADDR_BASE(0x43b86)
#define UI_LEN_IMAGE_BIN_CHECK_MARK_BIN            0xf6

#define UI_BUF_IMAGE_BIN_CLICK_BIN                 UI_ADDR_BASE(0x43c7c)
#define UI_LEN_IMAGE_BIN_CLICK_BIN                 0x14e

#define UI_BUF_IMAGE_BIN_CLICK_BJ_BIN              UI_ADDR_BASE(0x43dca)
#define UI_LEN_IMAGE_BIN_CLICK_BJ_BIN              0x369

#define UI_BUF_IMAGE_BIN_DIVIDER_UNCLICK_BIN       UI_ADDR_BASE(0x44133)
#define UI_LEN_IMAGE_BIN_DIVIDER_UNCLICK_BIN       0x369

#define UI_BUF_IMAGE_BIN_GROUP_1_BIN               UI_ADDR_BASE(0x4449c)
#define UI_LEN_IMAGE_BIN_GROUP_1_BIN               0x816

#define UI_BUF_IMAGE_BIN_LONG_BOTTON_BLUE_CLICK_BIN    UI_ADDR_BASE(0x44cb2)
#define UI_LEN_IMAGE_BIN_LONG_BOTTON_BLUE_CLICK_BIN    0x4d2

#define UI_BUF_IMAGE_BIN_LONG_BOTTON_BLUE_UNCLICK_BIN    UI_ADDR_BASE(0x45184)
#define UI_LEN_IMAGE_BIN_LONG_BOTTON_BLUE_UNCLICK_BIN    0x4de

#define UI_BUF_IMAGE_BIN_SETTING_BIN               UI_ADDR_BASE(0x45662)
#define UI_LEN_IMAGE_BIN_SETTING_BIN               0x2a5

#define UI_BUF_IMAGE_BIN_SETTING_BJ_BIN            UI_ADDR_BASE(0x45907)
#define UI_LEN_IMAGE_BIN_SETTING_BJ_BIN            0xb4

#define UI_BUF_IMAGE_BIN_UNCLICK_BIN               UI_ADDR_BASE(0x459bb)
#define UI_LEN_IMAGE_BIN_UNCLICK_BIN               0x15f

#endif
